spring:
  application:
    name: files-service
  datasource:
    url: jdbc:mysql://localhost:3306/file_service_db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

file:
  path: C:\\Users\\imran\\Documents